In [5]:
import numpy as np

In [28]:
a=np.array([1,2] )
b=np.array([np.array([1,2,2]),np.array([3,4,5])] )
print(b)
print(a.itemsize)

[[1 2 2]
 [3 4 5]]
8


In [45]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[1:-10])

[]


In [65]:
tdarray=np.array([[[1,2],[3,4]]])
print(tdarray[0,0:2,0])

[1 3]


In [68]:
ones = np.ones((4,3,2))
print(ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [178]:
random = np.random.randint(1,4 ,size=(2,2))
print(random)

[[1 2]
 [3 3]]


In [187]:
arr = np.array([[[1,2,3]]])
r1=np.repeat(arr,2 , axis=0)
print(r1)

[[[1 2 3]]

 [[1 2 3]]]


In [192]:
a=np.array([1,2,3,4])
# a+=2
# print(a+2)
# print(a)

In [193]:
print(a)

[1 2 3 4]


In [212]:
a=np.array([[7,2,3],[4,5,6],[12,13,14]])
# b=np.full((3,2),2)
# c=np.full((2,3),2)
# # print(b)
# print(a*c)

In [213]:
print(np.min(a , axis=1))

[ 2  4 12]


In [214]:
print(a)

[[ 7  2  3]
 [ 4  5  6]
 [12 13 14]]


In [218]:
print(np.sum(a , axis=1))

[12 15 39]


In [224]:
a=np.array([1.6])
a=a.astype('int32')
print(a)

[1]


In [234]:
a=np.zeros((6,5))
print(a)
for i in range(6):
    for j in range(5):
        a[i,j]=(j+1)+(5*i)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]


In [244]:
print(a[[0,1,2], 2:3])

[[ 3.]
 [ 8.]
 [13.]]
